all: clock.exe clocktsr.com

clock.exe: clock.asm clogic.inc cinstall.inc
   ml /Fl clock.asm

clocktsr.com: clocktsr.asm clogic.inc cinstall.inc
   ml /Fl clocktsr.asm

clean:
   del *.exe
   del *.com
   del *.lst
   del *.obj
















